import { Diary } from '../types/Diary'

export const initialDiaries: Diary[] = [
  {
    id: 1,
    company_id: 1,
    activity: { id: 1, name: 'Actividad 1' },
    name: 'Agenda 1',
    type_schedule: 'Por turnos',
    date_from: '01-06-2024',
    date_until: '01-07-2024',
    days_available: [
      { active: false, time_start: '07:00', time_end: '16:00' },
      { active: true, time_start: '17:00', time_end: '22:00' },
      { active: true, time_start: '12:00', time_end: '16:00' },
      { active: true, time_start: '07:00', time_end: '22:00' },
      { active: true, time_start: '09:00', time_end: '18:00' },
      { active: true, time_start: '07:00', time_end: '16:00' },
      { active: false, time_start: '07:00', time_end: '16:00' }
    ],
    repeat_for: 0,
    offer_days: [false, true, false, false, false, false, false],
    term_duration: 30,
    amount_of_people: 25,
    is_active: true,
    genre_exclusive: 'Masculino',
    works_holidays: false,
    observations: 'Observation 1'
  },
  {
    id: 3,
    company_id: 1,
    activity: { id: 2, name: 'Actividad 2' },
    name: 'Agenda 2',
    type_schedule: 'Libre',
    date_from: '01-06-2024',
    date_until: '01-07-2024',
    days_available: [
      { active: true, time_start: '09:00', time_end: '16:00' },
      { active: true, time_start: '06:00', time_end: '22:00' },
      { active: true, time_start: '06:00', time_end: '22:00' },
      { active: true, time_start: '06:00', time_end: '22:00' },
      { active: true, time_start: '06:00', time_end: '22:00' },
      { active: true, time_start: '06:00', time_end: '22:00' },
      { active: true, time_start: '09:00', time_end: '16:00' }
    ],
    repeat_for: 0,
    offer_days: [true, true, false, false, false, false, false],
    term_duration: 30,
    amount_of_people: 25,
    is_active: true,
    genre_exclusive: 'No',
    works_holidays: true,
    observations: 'Observation 2'
  },
  {
    id: 3,
    company_id: 1,
    activity: { id: 1, name: 'Actividad 1' },
    name: 'Agenda 3',
    type_schedule: 'Por turnos',
    date_from: '01-06-2024',
    date_until: '01-07-2024',
    days_available: [
      { active: true, time_start: '09:00', time_end: '16:00' },
      { active: false, time_start: '06:00', time_end: '22:00' },
      { active: false, time_start: '06:00', time_end: '22:00' },
      { active: false, time_start: '06:00', time_end: '22:00' },
      { active: false, time_start: '06:00', time_end: '22:00' },
      { active: false, time_start: '06:00', time_end: '22:00' },
      { active: true, time_start: '09:00', time_end: '16:00' }
    ],
    repeat_for: 0,
    offer_days: [false, true, false, false, false, false, false],
    term_duration: 30,
    amount_of_people: 25,
    is_active: true,
    genre_exclusive: 'Femenino',
    works_holidays: false,
    observations: 'Observation 1'
  },
  {
    id: 4,
    company_id: 1,
    activity: { id: 4, name: 'Actividad 4' },
    name: 'Agenda 4',
    type_schedule: 'Por turnos',
    date_from: '01-06-2024',
    date_until: '01-07-2024',
    days_available: [
      { active: true, time_start: '10:00', time_end: '15:00' },
      { active: false, time_start: '06:00', time_end: '22:00' },
      { active: true, time_start: '10:00', time_end: '15:00' },
      { active: false, time_start: '06:00', time_end: '22:00' },
      { active: true, time_start: '10:00', time_end: '15:00' },
      { active: false, time_start: '06:00', time_end: '22:00' },
      { active: true, time_start: '10:00', time_end: '15:00' }
    ],
    repeat_for: 0,
    offer_days: [false, true, false, false, false, false, false],
    term_duration: 30,
    amount_of_people: 25,
    is_active: true,
    genre_exclusive: 'Masculino',
    works_holidays: false,
    observations: 'Observation 1'
  },
  {
    id: 5,
    company_id: 1,
    activity: { id: 7, name: 'Actividad 7' },
    name: 'Agenda 5',
    type_schedule: 'Por turnos',
    date_from: '01-06-2024',
    date_until: '01-07-2024',
    days_available: [
      { active: false, time_start: '09:00', time_end: '16:00' },
      { active: true, time_start: '06:00', time_end: '22:00' },
      { active: false, time_start: '06:00', time_end: '22:00' },
      { active: true, time_start: '06:00', time_end: '22:00' },
      { active: false, time_start: '06:00', time_end: '22:00' },
      { active: true, time_start: '06:00', time_end: '22:00' },
      { active: false, time_start: '09:00', time_end: '16:00' }
    ],
    repeat_for: 0,
    offer_days: [false, true, false, false, false, false, false],
    term_duration: 30,
    amount_of_people: 25,
    is_active: true,
    genre_exclusive: 'No',
    works_holidays: false,
    observations: 'Observation 1'
  }
]
